Setup Checkout (Update Payment Method)
getopenpay/openpay-js-react pull request #36
Opened 2024-09-05 13:36 UTC by zeyarpaing

2024-09-09 13:53 UTC, zeyarpaing commented
Docs Link: https://docs.getopenpay.com/docs/update-credit-card-payment-method

2024-09-09 16:58 UTC, syvlabs requested changes

2024-09-09 16:58 UTC, syvlabs commented on example/src/app/page.tsx
> +type OnSetupCheckoutSuccess = (paymentMethodId: string) => void;
Again let's rename this to "SetupPaymentMethodSuccess"

2024-09-09 16:58 UTC, syvlabs commented on example/src/app/page.tsx
> +  onSetupCheckoutSuccess: OnSetupCheckoutSuccess;
Same

2024-09-09 16:58 UTC, syvlabs commented on example/src/app/page.tsx
> +  const { token, separateFrames, onCheckoutSuccess, onSetupCheckoutSuccess } = props;
Same

2024-09-09 16:58 UTC, syvlabs commented on example/src/app/page.tsx
> +      onSetupCheckoutSuccess={(paymentMethodID) => {
Same for all of these

2024-09-09 16:58 UTC, syvlabs commented on example/src/app/page.tsx
> +      baseUrl={'http://localhost:3030'}
Is this `baseUrl` only for dev and stg? Not applicable to prod right?

2024-09-09 17:03 UTC, syvlabs requested changes

2024-09-09 17:03 UTC, syvlabs commented on lib/components/form.tsx
> +      } else if (eventType === EventType.enum.SETUP_CHECKOUT_SUCCESS) {
Can we rename to "setup payment method"? Hopefully its easy

2024-09-09 17:03 UTC, syvlabs commented on lib/components/form.tsx
> +    if (iframes.length > 0 && iframes.length === Object.keys(eventTargets).length) {
Why did we add the `> 0` check? There's a case when both `iframes.length` and eventTargets length are both 0?

2024-09-10 12:32 UTC, zeyarpaing commented on example/src/app/page.tsx
> +      baseUrl={'http://localhost:3030'}
sorry, it's just testing. forgot to remove.

2024-09-11 09:25 UTC, syvlabs commented on example/src/app/page.tsx
> +    if (totalAmountAtoms) setAmount(`${currency ? `${currency.toUpperCase()} ` : '$'}${totalAmountAtoms / 100}`);
Please avoid one-line `if`s

Should be

```
if (totalAmountAtoms) {
    setAmount(...)
}
```

2024-09-11 09:25 UTC, syvlabs commented on example/src/app/page.tsx
> +    if (!token) return;
Same here

2024-09-11 09:27 UTC, syvlabs commented on lib/components/form.tsx
> +    if (iframes.length > 0 && iframes.length === Object.keys(eventTargets).length) {
Oh that's tricky, can you add a const to serve as a comment? something like

```
const areiFramesAllLoaded = ...

if (iFramesAllLoaded) {
...
}
```

2024-09-12 04:35 UTC, syvlabs approved these changes

2024-09-12 04:35 UTC, syvlabs commented on example/src/app/page.tsx
> +      setAmount(`${currency ? `${currency.toUpperCase()} ` : '$'}${totalAmountAtoms / 100}`);
Sorry one very last, please get the `atomToCurrency` from either CDE or Conn-to, then use it here instead of `/ 100`

2024-09-12 12:20 UTC, merged