Iterate 3ds embed popup
getopenpay/openpay-js-react pull request #68
Opened 2024-11-18 15:00 UTC by zeyarpaing

2024-11-20 07:25 UTC, syvlabs requested changes

2024-11-20 07:25 UTC, syvlabs commented on packages/vanilla/3ds-elements/frame.ts
> +      // console.error('🔴 CDE connection failed, continuing to poll...');
Does this ever happen?

2024-11-20 07:25 UTC, syvlabs commented on packages/vanilla/3ds-elements/frame.ts
> +  style.textContent = `
Not sure it's a good idea to define the styles here, can we not use tailwind or move it to an external .css file?

2024-11-20 07:25 UTC, syvlabs commented on packages/vanilla/3ds-elements/frame.ts
> +  const shadowHost = document.createElement('div');
Can we use template tags so it's more maintainable? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

2024-11-20 07:25 UTC, syvlabs commented on packages/vanilla/3ds-elements/frame.ts
> +  function cleanup() {
Please use arrow functions `const cleanup = () => {...` instead of `function`

2024-11-20 07:25 UTC, syvlabs commented on packages/vanilla/3ds-elements/frame.ts
> +  return new Promise((resolve) => {
Better to refactor these polling + event listeners into another file

2024-11-20 07:27 UTC, zeyarpaing commented on packages/vanilla/3ds-elements/frame.ts
> +      // console.error('🔴 CDE connection failed, continuing to poll...');
yes, as long as it doesn't reach to CDE `success` / `failure` page.

2024-11-22 13:12 UTC, syvlabs approved these changes

2024-11-22 13:24 UTC, merged